# Generated by Django 4.2.5 on 2024-02-27 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=100, verbose_name='Surname')),
                ('id_user', models.ForeignKey(blank=True, help_text='выберите id пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id User')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name_department', models.CharField(help_text='Введите название отдела', max_length=100, primary_key=True, serialize=False, verbose_name='Название отдела')),
                ('brands', models.ManyToManyField(to='my_project.brand')),
                ('employee', models.ForeignKey(help_text='выберите id сотрудника', on_delete=django.db.models.deletion.CASCADE, to='my_project.employee', verbose_name='Employee')),
            ],
        ),
    ]
