# Generated by Django 4.2.5 on 2024-02-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0002_employee_department'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
    ]
