# Generated by Django 4.2.5 on 2024-03-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0003_alter_department_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='name_of_brand',
        ),
    ]
